export const dummyData = {
  users: [
    {
      id: "1",
      name: "John Doe",
      email: "john@example.com",
      status: "Active",
      joinDate: "2024-01-01",
      lastLogin: "2024-01-10",
    },
    {
      id: "2",
      name: "Alice Brown",
      email: "alice@example.com",
      status: "Active",
      joinDate: "2024-01-04",
      lastLogin: "2024-01-12",
    },
    {
      id: "3",
      name: "Eva Green",
      email: "eva@example.com",
      status: "Suspended",
      joinDate: "2024-01-06",
      lastLogin: "2024-01-08",
    },
  ],
  transactions: [
    {
      id: "TRX001",
      amount: 99.99,
      userName: "John Doe",
      userEmail: "john@example.com",
      publisherName: "Acme Publishing",
      date: "2024-01-10",
      bookTitle: "The Great Adventure",
      paymentMethod: "Credit Card",
    },
    {
      id: "TRX002",
      amount: 45.5,
      userName: "Alice Brown",
      userEmail: "alice@example.com",
      publisherName: "Wonderland Books",
      date: "2024-01-11",
      bookTitle: "Mystery of the Ages",
      paymentMethod: "PayPal",
    },
    {
      id: "TRX003",
      amount: 150.0,
      userName: "Bob Wilson",
      userEmail: "bob@example.com",
      publisherName: "Science Press",
      date: "2024-01-12",
      bookTitle: "Science Today",
      paymentMethod: "Credit Card",
    },
    {
      id: "TRX004",
      amount: 75.25,
      userName: "Eva Green",
      userEmail: "eva@example.com",
      publisherName: "History House",
      date: "2024-01-13",
      bookTitle: "History Chronicles",
      paymentMethod: "Debit Card",
    },
    {
      id: "TRX005",
      amount: 199.99,
      userName: "Charlie Davis",
      userEmail: "charlie@example.com",
      publisherName: "Future Tech Publications",
      date: "2024-01-14",
      bookTitle: "Future Tech",
      paymentMethod: "Credit Card",
    },
  ],
  reviews: [
    {
      id: "REV001",
      content: "Excellent book, highly recommended!",
      rating: 5,
      status: "approved",
      date: "2024-01-10",
      bookTitle: "The Great Adventure",
      reviewer: "John Doe",
    },
    {
      id: "REV002",
      content: "Good read but could be better",
      rating: 3,
      status: "pending",
      date: "2024-01-11",
      bookTitle: "Mystery of the Ages",
      reviewer: "Alice Brown",
    },
    {
      id: "REV003",
      content: "Not what I expected",
      rating: 2,
      status: "rejected",
      date: "2024-01-12",
      bookTitle: "Science Today",
      reviewer: "Bob Wilson",
    },
    {
      id: "REV004",
      content: "Amazing content and presentation",
      rating: 5,
      status: "approved",
      date: "2024-01-13",
      bookTitle: "History Chronicles",
      reviewer: "Eva Green",
    },
    {
      id: "REV005",
      content: "Very informative",
      rating: 4,
      status: "pending",
      date: "2024-01-14",
      bookTitle: "Future Tech",
      reviewer: "Charlie Davis",
    },
  ],
  reportReviews: [
    {
      id: "REP001",
      content:
        "This comment contains offensive language and should be removed.",
      reportedItemType: "Comment",
      reportedItemId: "CMT123",
      reporterName: "John Doe",
      reporterEmail: "john@example.com",
      status: "pending",
      date: "2024-01-10",
      severity: "high",
    },
    {
      id: "REP002",
      content:
        "This blog post appears to be spam and unrelated to our platform.",
      reportedItemType: "Blog Post",
      reportedItemId: "BP456",
      reporterName: "Alice Brown",
      reporterEmail: "alice@example.com",
      status: "under_review",
      date: "2024-01-11",
      severity: "medium",
    },
    {
      id: "REP003",
      content: "User is repeatedly posting inappropriate content.",
      reportedItemType: "User",
      reportedItemId: "USR789",
      reporterName: "Bob Wilson",
      reporterEmail: "bob@example.com",
      status: "resolved",
      date: "2024-01-12",
      severity: "high",
    },
    {
      id: "REP004",
      content:
        "This comment is spreading misinformation about health practices.",
      reportedItemType: "Comment",
      reportedItemId: "CMT234",
      reporterName: "Eva Green",
      reporterEmail: "eva@example.com",
      status: "pending",
      date: "2024-01-13",
      severity: "high",
    },
    {
      id: "REP005",
      content: "Potential copyright infringement in this blog post.",
      reportedItemType: "Blog Post",
      reportedItemId: "BP567",
      reporterName: "Charlie Davis",
      reporterEmail: "charlie@example.com",
      status: "under_review",
      date: "2024-01-14",
      severity: "medium",
    },
  ],
  publishers: [
    {
      id: "1",
      name: "Bob Wilson",
      email: "bob@example.com",
      status: "Active",
      joinDate: "2024-01-03",
      lastLogin: "2024-01-09",
    },
    {
      id: "2",
      name: "Charlie Davis",
      email: "charlie@example.com",
      status: "Active",
      joinDate: "2024-01-05",
      lastLogin: "2024-01-10",
    },
    {
      id: "3",
      name: "Diana Evans",
      email: "diana@example.com",
      status: "Inactive",
      joinDate: "2024-01-07",
      lastLogin: "2024-01-11",
    },
    {
      id: "4",
      name: "Frank Miller",
      email: "frank@example.com",
      status: "Active",
      joinDate: "2024-01-08",
      lastLogin: "2024-01-13",
    },
    {
      id: "5",
      name: "Grace Lee",
      email: "grace@example.com",
      status: "Active",
      joinDate: "2024-01-09",
      lastLogin: "2024-01-14",
    },
  ],
};

export type User = (typeof dummyData.users)[0];
export type Transaction = (typeof dummyData.transactions)[0];
export type Review = (typeof dummyData.reviews)[0];
export type ReportReview = (typeof dummyData.reportReviews)[0];
export type Publisher = (typeof dummyData.publishers)[0];
